[package]
name = "nag763"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.3.0"
leptos = { version = "0.6.11", features = ["csr"] }
leptos-use = "0.10.10"
leptos_i18n = { version = "0.3.3", default-features = false, features = ["csr", "yaml_files", "cookie"] }
leptos_router = { version = "0.6.11", features = ["csr"] }
wasm-bindgen = "0.2.92"

[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "fr"]
