[package]
name = "nag763"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.11", features = ["csr"] }
leptos_i18n = { version = "0.3.3", default-features = false, features = ["csr", "yaml_files", "cookie"] }
wasm-bindgen = "0.2.92"

[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "fr"]
