name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install target
      run: rustup target add wasm32-unknown-unknown
    - name: Install trunk
      run: cargo install trunk
    - name: Build
      run: trunk build --release -M
    
