name: Deploy Frontend

on:
  push:
    branches: ["main"]
    paths:
      - 'front/**'
      - '.github/workflows/deploy-front.yml'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm deps
        run: npm i
        working-directory: ./front
      - name: Build
        env:
          LAMBDA_URL: ${{ secrets.PUBLIC_AGENT_ENDPOINT }}
        run: npm run build
        working-directory: ./front
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./front/dist

  deploy-s3:
    needs: build-front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: eu-central-1
      - name: Sync files to S3 bucket
        run: aws s3 sync ./dist s3://nag763 --delete