name: Deploy Lambda

on:
  push:
    branches: ["main"]
    paths:
      - 'agent/**'
      - '.github/workflows/deploy-lambda.yml'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install requirements
        run: uv pip install -r pyproject.toml --target .
        working-directory: agent

      - name: Zip agent directory
        run: |
          cd agent
          zip -r ../agent.zip .
      - name: Deploy Lambda
        run: aws lambda update-function-code --function-name nag763-agent --zip-file fileb://agent.zip
